format = """
$hostname$directory $git_branch $git_status $git_metrics\
$fill\
$kubernetes$azure$aws
$character
"""

command_timeout = 5000

[character]
success_symbol = "[>](bold green)"
error_symbol = "[!](bold #ff00ff)"
vicmd_symbol = "[#](bold #00ffff)"

[hostname]
ssh_only = true
trim_at = '.'
style = 'bold fg:#ff9e64'
format = '[ssh:$hostname]($style) '
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = true
home_symbol = '~'
style = 'fg:#7aa2f7'
read_only = ' (ro)'
read_only_style = 'fg:#f7768e'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '%'
truncation_length = 30
truncation_symbol = ''
style = 'fg:#7aa2f7'
format = '[@ $branch(:$remote_branch)]($style) '

[git_status]
style = 'fg:#e0af68'
conflicted = '='
ahead = '^${count}'
behind = 'v${count}'
diverged = '<>'
up_to_date = 'ok'
untracked = '?'
stashed = '$'
modified = '*${count}'
renamed = '>>'
deleted = 'x'
format = '([$all_status$ahead_behind]($style))'

[git_metrics]
added_style = 'fg:#9ece6a'
deleted_style = 'fg:#9ece6a'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = ' '

[kubernetes]
symbol = 'k8s:'
format = '[$symbol$context(\\($namespace\\))]($style) '
style = 'fg:#9ece6a'
disabled = false
contexts = [
  { context_pattern = ".*prod.*", style = 'bold fg:#f7768e'},
]

[aws]
symbol = 'aws:'
format = '[$symbol($profile)]($style) '
style = 'fg:#9ece6a'
disabled = false

[azure]
symbol = 'az:'
format = '[$symbol($subscription)]($style) '
style = 'fg:#9ece6a'
disabled = false
