format = """
[](fg:#7aa2f7)$os[ ](fg:#7aa2f7)$hostname $directory $git_branch $git_status $git_metrics\
$fill\
$battery [](fg:#9ece6a)$kubernetes[](fg:#9ece6a)[](fg:#9ece6a)$aws$azure[](fg:#9ece6a) 
$character
"""

command_timeout = 5000

[os]
format = "[$symbol]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[hostname]
ssh_only = true          # SSH接続時のみ表示する場合は true
trim_at = '.'             # 最初の '.' までを表示（FQDN を短縮）
style = 'fg:#7aa2f7'
format = '[$hostname]($style)'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%m-%d %a %H:%M'
utc_time_offset = '+9'

[directory]
truncation_length = 3
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = true
home_symbol = ' ~' # nf-costum-home
style = 'fg:#7aa2f7'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '  ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 30
truncation_symbol = ''
style = 'fg:#7aa2f7'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#e0af68'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a'
deleted_style = 'fg:#9ece6a'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = ' '

[character]
# fish の場合
# success_symbol = "[ ❯](green)"
# error_symbol = "[❮](#ff00ff)"
# vicmd_symbol = "[ ❯](#00ffff)"

# nushell の場合
success_symbol = "[](green)"
error_symbol = "[](#ff00ff)"
vicmd_symbol = "[](#00ffff)"

[memory_usage]
disabled = false
threshold = 0
format = "[$ram( $percentage%)]($style) "

[battery]
full_symbol = ' '
charging_symbol = '󱐋 '
discharging_symbol = '󱓞 '
empty_symbol = ' '
format = '[  $symbol$percentage]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o

[[battery.display]]
threshold = 100
style = 'fg:#c0c0c0'

[python]
symbol = ' ' # nf-dev-python
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
pyenv_version_name = false
style = 'fg:#1a1b26 bg:#9ece6a'

[kubernetes]
symbol = '󱃾 '
format = '[ $symbol$context(\($namespace\))]($style)'
style = 'fg:#1a1b26 bg:#9ece6a'
disabled = false
contexts = [
  { context_pattern = "prod", style = '#CC0033 bg:#9ece6a'},
]

[aws]
symbol = ' '
format = '[$symbol($profile)]($style)'
#format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = 'fg:#1a1b26 bg:#9ece6a'
disabled = false

[azure]
symbol = ' '
format = '[$symbol($subscription)]($style)'
style = 'fg:#1a1b26 bg:#9ece6a'
disabled = true

[cmd_duration]
min_time = 1000
style = 'fg:#e0af68'
format = "[  󰅕 $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

#[custom.disk_space]
# command = "df -h / | tail -1 | awk '{print $4}'"
#command = "df -h / | tail -1 | awk '{print $4 \"/\" $2 }'"
#when = "true"
#format = " [  󰥠 $output](bold blue)"

